<div class="row">
	<div class="col-sm-2"> </div>
	<div class="col-sm-8 well">
		<legend><h2><b>REGISTRACIJA</b></h2></legend>
		<a class="btn btn-primary" href="signup/facebook" style="margin-bottom: 5%;">Dohvati podatke s Facebook računa</a>
       <div style="text-align: center; font-size: larger;">
         <b class="error-message"><? $this->flashSession->output(); ?></b>
       </div>
       <form action="/signup/register" method = "POST" enctype="multipart/form-data">
		
			<div class="col-sm-10" >
				<div class="input-group">
                    <label class="input-label" for = "first_name">Ime:</label>
                    <input class="input" type="text" name="first_name" value="<?php echo $this->session->get('first_name')?>" required>
                </div>
                <div class="input-group">
				    <label class="input-label" for = "last_name">Prezime:</label>
                    <input class="input" type="text" name="last_name" value="<?php echo $this->session->get('last_name')?>" required>
                </div>
                <div class="input-group">
    				<label class="input-label">E-mail:</label>
                    <input class = "input" type="text" name="email" value="<?php echo $this->session->get('email')?>" required>
                </div>
                <div class="input-group">
                    <label class="input-label">Ponovite E-mail:</label>
                    <input class = "input" type="text" name="r-email" value="<?php echo $this->session->get('email')?>" required>
                </div>
                <div class="input-group">
                    <label class="input-label">Lozinka:</label>
                    <input class="input" type="password" name="password" required>
                </div>
                <div class="input-group">
                    <label class="input-label">Ponovite Lozinku:</label>
                    <input class="input" type="password" name="r-password"  required>
                </div>
                <div class="input-group">
				    <label class="input-label">Tip korisnika:</label>
                    <input id = "type_user" type="radio" name="Tip" value="Korisnik" onchange="userInput()" checked> Korisnik
                    <input type="radio" name="Tip" value="Vlasnik" onchange="userInput()"> Vlasnik
                </div>

			</div>

			<div id="korisnik" class="col-sm-8">
				<br>
				<legend style="color: #337ab7;">Korinsik</legend>
				<div class="col-sm-6" align="right">
					<label class="input-label">Adresa:</label> <br>
					<label class="input-label">Grad:</label> <br>
				</div>
				<div class="col-sm-4">
					<input type="text" name="address">
					<input type="text" name="hometown">
				</div>
                <div style="margin-top: 100px; margin-left: 48%;">
				    <button name="submit" class="btn btn-primary" style="width: 150px;">Potvrdi</button>
                </div>
            </div>

			<div id="vlasnik" class="col-sm-8">
			<br>
			<legend style="color: #337ab7;">Vlasnik</legend>
				<div class="col-sm-6" align="right">
					<label class="input-label">Adresa:</label> <br>
					<label class="input-label">Grad:</label> <br>
					
				</div>
				<div class="col-sm-4">
					<input type="text" name="address">
					<input type="text" name="hometown" value="<?php echo $this->session->get('hometown')?>">
				</div>
			<legend style="margin-top: 35%; color: #337ab7;">Info kluba</legend>
                <div class="input-group">
                    <label class="input-label">Ime Kluba:</label>
                    <input class="input" type="text" name="bar[ime]">
                </div>
                <div class="input-group">
                    <label class="input-label">Adresa:</label>
                    <input class="input" type="text" name="bar[adresa]">
                    <p style="font-size: 12px;">Oblik: Ulica XX</p>
                </div>
                <div class="input-group">
                    <label class="input-label">Grad:</label>
                    <input class="input" type="text" name="bar[grad]" >
                    <p style="font-size: 12px;">Oblik: Rijeka,Zagreb,Split</p>

                </div>
                <div class="input-group">
                    <label class="input-label">Telefon:</label>
                    <input class="input" type="text" name="bar[telefon]">
                    <p style="font-size: 12px;">Oblik: 051-XXXXXX ili 09X-XXXXXXX</p>
                </div>
                    <label class="input-label">Opis:</label><br>
                    <textarea style="resize: none; margin-top: 5%;" cols="30" rows="10" maxlength="256" name="bar[opis]"></textarea>
                <br>
                <br>
				<label>Upload slika(max 5): </label>
				<input class="file" type="file" id="files" name="files[]" multiple onchange = "checkFiles(this.files)" accept = "image/*"/>
				<div id = "img-status"></div> <br />
				<output id="list"></output>
				<script>
					 function checkFiles(files) {       
							if(files.length>4) {
							document.getElementById("img-status").innerHTML = "Max 5 slika";
							files.slice(0,4);
							return false;
							}       
					}
					
					function handleFileSelect(evt) {
						var files = evt.target.files;

						for (var i = 0, f; f = files[i],i < 5; i++) {
							var control = document.getElementById("list").childElementCount;
							if(control > 4) break;
							
							if (!f.type.match('image.*')) {
								continue;
								}

						var reader = new FileReader();
							reader.onload = (function(theFile) {
									return function(e) {
									var span = document.createElement('span');
									span.innerHTML = ['<img class="images" src="', e.target.result,
									'" title="', escape(theFile.name), '"/>'].join('');
									document.getElementById('list').insertBefore(span, null);
						};})(f);
							reader.readAsDataURL(f);
					}}
					document.getElementById('files').addEventListener('change', handleFileSelect, false);
			</script>
			<button name="submit" class="btn btn-primary">Potvrdi</button>
			</div>	
			
		</form>
	</div>
	<div class="col-sm-2"> </div>
</div>



</body>
</html>
