<div class="container">
    <h2>Događaji</h2>
    <a href="/admin/addDogadaj#bot">
        <button nam
        "del0" class='btn btn-info glyphicon glyphicon-calendar'></button></a>
    <table class="table">
        <thead>
        <tr>
            <th>#</th>
            <th>Naziv</th>
            <th>Vrijeme</th>
            <th>Rezervacija</th>
            <th>ID_Kluba</th>
            <th>Opis</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $item) { ?>
            <form action="/admin/updateDogadaj/<?php echo $item->id_Dogadaj; ?>" method="POST"
                  enctype="multipart/form-data">
                <tr>
                    <td><?php echo $item->id_Dogadaj; ?></td>
                    <td>
                        <input type="text" name='naziv' class="form-control" value="<?php echo $item->naziv; ?>"/>
                    </td>
                    <td>
                        <input type="text" name='vrijeme' class="form-control" value="<?php echo $item->vrijeme; ?>"/>
                    </td>
                    <td>
                        <input type="text" name='rezervacija' class="form-control"
                               value="<?php echo $item->rezervacija; ?>"/>
                    </td>
                    <td>
                        <input type="text" name='id_Klub' class="form-control" value="<?php echo $item->id_Klub; ?>"/>
                    </td>
                    <td><textarea name="opis" class="form-control"><?php echo $item->opis; ?> </textarea></td>
                    <td>
                        <button name='submit' class='btn btn-danger glyphicon glyphicon-edit row-edit'></button>
                    </td>
            </form>
            <td><a href="/admin/deleteDogadaj/<?php echo $item->id_Dogadaj; ?>">
                    <button nam
                    "del0" class='btn btn-danger glyphicon glyphicon-trash row-remove'></button></a></td>
            </tr>

        <?php } ?>
        </tbody>
    </table>
    <a name="bot">
</div>


<div align="center">
    <ul class="pagination">
        <li><a href="/admin/dogadaj">First</a></li>
        <li><a href="/admin/dogadaj?page=<?= $page->before; ?>">&laquo;</a></li>
        <li><a href="/admin/dogadaj?page=<?= $page->next; ?>">&raquo;</a></li>
        <li><a href="/admin/dogadaj?page=<?= $page->last; ?>">Last</a></li>
    </ul>
    <br>
    <?php echo "You are in page ", $page->current, " of ", $page->total_pages; ?>
</div>