<!DOCTYPE html>
<html>
<head>
	<title>Club</title>
	<?php $this->assets->outputCss();?>
	<meta charset="utf-8" />
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />

	<style type="text/css">
		.follow-btn{
			color: white;
			width: 65%;
			margin-top: 10%;

		}
	</style>

</head>
<body> 

<!-- NAVIGACIJSKI MENI mozda bolje include jer se ponavlja-->
<?php include("../app/includes/base.php"); ?>
<div class = "container">
	<div class="col-sm-8" align="left">
		<a href="/admin/klub" class="btn btn-primary follow-btn">Uredi Klubove</a>
		<a href="/admin/korisnik" class="btn btn-primary follow-btn">Uredi Korisnike</a>
		<a href="/admin/dogadaj" class="btn btn-primary follow-btn">Uredi Dogadaje</a>
	</div>
</div>




</body>
</html>
