<div class="container">
  <h2>Klubovi</h2> 
  <a href="/admin/addKlub#bot"><button nam"del0" class='btn btn-info glyphicon glyphicon-home'></button></a>       
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Ime</th>
        <th>Adresa</th>
        <th>Ocjena</th>
        <th>ID_Vlasnika</th>
        <th>Opis</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $item){ ?>
    <form action="/admin/updateKlub/<?php echo $item->id_Klub; ?>" method = "POST" enctype="multipart/form-data">
      <tr>
        <td><?php echo $item->id_Klub; ?></td>
        <td>
        	<input type="text" name='ime' class="form-control" value="<?php echo $item->ime; ?>"/>
        </td>
        <td>
        	<input type="text" name='adresa' class="form-control" value="<?php echo $item->adresa; ?>"/>
        </td>
        <td>
		    <input type="text" name='ocjena' class="form-control" value="<?php echo $item->ocjena; ?>"/>    	
        </td>
        <td>
			<input type="text" name='id_Vlasnik' class="form-control" value="<?php echo $item->id_Vlasnik; ?>"/>
        </td>
        <td><textarea name="opis" class="form-control"><?php echo $item->opis; ?> </textarea></td>
        <td><button name='submit' class='btn btn-danger glyphicon glyphicon-edit row-edit'></button></td>
    </form>
        <td><a href="/admin/deleteKlub/<?php echo $item->id_Klub; ?>"><button nam"del0" class='btn btn-danger glyphicon glyphicon-trash row-remove'></button></a></td>
      </tr>
    
      <?php } ?>
    </tbody>
  </table>
  <a name="bot">
</div>


<div align = "center">
    <ul class="pagination">
        <li><a href="/admin/klub">First</a></li>
        <li><a href="/admin/klub?page=<?= $page->before; ?>">&laquo;</a></li>
        <li><a href="/admin/klub?page=<?= $page->next; ?>">&raquo;</a></li>
        <li><a href="/admin/klub?page=<?= $page->last; ?>">Last</a></li>
    </ul>
    <br>
    <?php echo "You are in page ", $page->current, " of ", $page->total_pages; ?>
</div>
