<!DOCTYPE html>
<html>
<head>
	<title>Club</title>
	<?php $this->assets->outputCss();?>
	<meta charset="utf-8" />
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />

	<style type="text/css">
		.follow-btn{
			color: white;
			width: 65%;
			margin-top: 10%;

		}
	</style>

</head>
<body> 

<!-- NAVIGACIJSKI MENI mozda bolje include jer se ponavlja-->
<?php include("../app/includes/base.php"); ?>

<div class="container">
  <h2>Klubovi</h2>           
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Ime</th>
        <th>Adresa</th>
        <th>Ocjena</th>
        <th>ID_Vlasnika</th>
        <th>Opis</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($items as $item){ ?>
      <tr>
        <td><?php echo $item->id_Klub; ?></td>
        <td>
        	<input type="text" name='name0'  placeholder='Name kurac' class="form-control" value="<?php echo $item->ime; ?>"/>
        </td>

        <td>
        	<input type="text" name='name0'  placeholder='Name k' class="form-control" value="<?php echo $item->adresa; ?>"/>
        </td>
        <td>
		    <input type="text" name='name0'  placeholder='Name' class="form-control" value="<?php echo $item->ocjena; ?>"/>    	
        </td>
        <td>
			<input type="text" name='name0'  placeholder='Name' class="form-control" value="<?php echo $item->id_Vlasnik; ?>"/>
        </td>
        <td><textarea name="desc0" placeholder="Description" class="form-control"><?php echo $item->opis; ?> </textarea></td>
        <td><a href="/index"><button nam"del0" class='btn btn-danger glyphicon glyphicon-edit row-edit'></button></a></td>
        <td><a href="/admin/deleteKlub/<?php echo $item->id_Klub; ?>"><button nam"del0" class='btn btn-danger glyphicon glyphicon-remove row-remove'></button></a></td>
      </tr>
      <?php } ?>
    </tbody>
  </table>
</div>

</body>
</html>
