<!DOCTYPE html>
<html>
<head>
	<title>Club</title>
	<?php $this->assets->outputCss();?>
	<meta charset="utf-8" />
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />

	<style type="text/css">
		.follow-btn{
			color: white;
			width: 65%;
			margin-top: 10%;

		}
	</style>

</head>
<body> 

<!-- NAVIGACIJSKI MENI mozda bolje include jer se ponavlja-->
<?php include("../app/includes/base.php"); ?>

<div class="container">
  <h2>Korisnici</h2>           
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Ime</th>
        <th>Email</th>
        <th>Password</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($items as $item){ ?>
    <form action="/admin/updateKorisnik/<?php echo $item->id_Korisnik; ?>" method = "POST" enctype="multipart/form-data">
      <tr>
        <td><?php echo $item->id_Korisnik; ?></td>
        <td>
        	<input type="text" name='ime' class="form-control" value="<?php echo $item->ime; ?>"/>
        </td>
        <td>
        	<input type="text" name='email' class="form-control" value="<?php echo $item->email; ?>"/>
        </td>
        <td>
		    <input type="text" name='password' class="form-control" value="<?php echo $item->password; ?>"/>    	
        </td>
        <td><button name='submit' class='btn btn-danger glyphicon glyphicon-edit row-edit'></button></td>
    </form>
        <td><a href="/admin/deleteKorisnik/<?php echo $item->id_Korisnik; ?>"><button nam"del0" class='btn btn-danger glyphicon glyphicon-remove row-remove'></button></a></td>
      </tr>
    
      <?php } ?>
    </tbody>
  </table>
</div>

</body>
</html>
