<!DOCTYPE html>
<html>
<head>
	<title>Club</title>
	<?php $this->assets->outputCss();?>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
</head>
<body> 

<!-- NAVIGACIJSKI MENI mozda bolje include jer se ponavlja-->
<?php include("../app/includes/base.php"); ?>


<!-- CONTAINER ZA PRINTANJE POJEDNIOG KLUBA, MOZDA BOLJE U MODELU DODATI FUNKCIJU PRINT ZA SVAKI POSEBNO -->
<?php include("../app/includes/bars.php"); ?>

<!-- PAGINACIJA mozda bolje include jer se ponavlja-->
<div align = "center">
    <ul class="pagination">
        <li><a href="#">&laquo;</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">&raquo;</a></li>
    </ul>
</div>

</body>
</html>
