<!DOCTYPE html>
<html>
<head>
	<title>Club</title>
	<?php $this->assets->outputCss();?>
</head>
<body> 

<nav class="navbar navbar-default">
  	<div class = "container-fluid">
  	<div class = "navbar-header">
  		<a class = "navbar-brand" href="#">Home</a>
  	</div>
		<ul class = "list-inline">
		  <li><a href="#">Menu 1</a></li>
		  <li><a href="#">Menu 2</a></li>
		  <li><a href="#">Menu 3</a></li>
		  <li><a href="#">Menu 4</a></li>
		</ul>
		<ul class = "list-inline">
			<li><a href="login"><span class = "glyphicon glyphicon-log-in">Prijava</span></a></li>
			<li><a href="signup"><span class = "glyphicon glyphicon-user">Registracija</span></a></li>
		</ul>
	</div>
</nav>
<div class = "container">
<div class = "row well">
	<div class = "col-sm-4">
		<img src="img/images.png" class = "img-circle">
	</div>
	<div class = "col-sm-8">
		<h2>Rakhia bar</h2><br>
		<h5>Adresa:</h5>
		<h5>Ocjena:</h5>
		<h5>Opis:</h5>
	</div>	
</div>

<div align = "center">
    <ul class="pagination">
        <li><a href="#">&laquo;</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">&raquo;</a></li>
    </ul>
</div>


</body>
</html>
