<div class="col-sm-2">
    <form action="addevents/add" method = "POST" enctype="multipart/form-data">
        <div class="col-sm-6" align="right">
            <label class="input-label">Vrijeme:</label> <br>
            <label class="input-label">Naziv:</label> <br -->
            <label class="input-label">ID Kluba:</label> <br>
            <label class="input-label">Opis:</label> <br>
        </div>
        <div class="col-sm-4">
            <input type="text" name="vrijeme">
            <input type="text" name="naziv">
            <input type="text" name="id_Klub">
            <textarea style="resize: none; margin-top: 5%;" cols="30" rows="10" maxlength="256" name="opis"></textarea>
            
        </div>
        <button name="submit" class="btn btn-primary">Potvrdi</button>
    </form>
</div>
