<!-- CONTAINER ZA PRINTANJE POJEDNIOG EVENTA, MOZDA BOLJE U MODELU DODATI FUNKCIJU PRINT ZA SVAKI POSEBNO -->
<?php foreach($page->items as $item){ ?>
    <div class = "container">
        <div class = "row well">
            <div class = "col-sm-4">
                <img src="img/images.png" class = "img-circle">
            </div>
            <div class = "col-sm-8">
                <h2><?php echo $item->naziv; ?></h2><br> <!-- LINK NA STRANICU S DETALJIMA -->
                <h5>Datum: <?php echo $item->vrijeme; ?></h5>
                <h5>Opis:</h5>
                <p><?php echo $item->opis; ?></p>
                <h5>Broj dolazaka: <?php echo $item->rezervacija; ?></h5>
                <div class="col-sm-8" align="right">

                    <? if (!Rezervacija::isReserved($this->session->get("id"),$item->id_Dogadaj)): ?>

                        <a href="/events/reserve/<?= $item->id_Dogadaj; ?>" class="btn btn-primary follow-btn">Rezerviraj</a>

                    <? else: ?>

                        <a href="/events/unreserve/<?= $item->id_Dogadaj; ?>" class="btn btn-primary follow-btn">Odrezerviraj</a>

                    <? endif ?>

                    <a href="/events/edit/<?= $item->id_Dogadaj; ?>" class="btn btn-primary follow-btn">uredi</a>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

<!-- PAGINACIJA  mozda bolje include-->
<div align = "center">
    <ul class="pagination">
        <li><a href="/events">First</a></li>
        <li><a href="/events?page=<?= $page->before; ?>">&laquo;</a></li>
        <li><a href="/events?page=<?= $page->next; ?>">&raquo;</a></li>
        <li><a href="/events?page=<?= $page->last; ?>">Last</a></li>
    </ul>
    <br>
    <?php echo "You are in page ", $page->current, " of ", $page->total_pages; ?>
</div>