<head>
  
  <link rel="stylesheet" type="text/css" href="css/404.css">
</head>

<body>
<div class="wrapper row2">
<div id="container" class="clear">
<section id="fof" class="clear">
  <div class="positioned">
    <div class="hgroup">
      <h1>404 Error</h1>
      <h2>DOH! Page Not Found&hellip;</h2>
    </div>
    <p>The Page You Requested Could Not Be Found On Our Server</p>
  </div>
</section>
</div>
</div>
</body>