<div class="container row">
    <div class="card bg-light text-dark" style="margin-left: 30%; margin-top: 5%; width: 40%;">
        <div class="card-body">
            <form method="post" action="/user/update/<?= $user->id_Korisnik; ?>">
                Ime:<br><input type="text" name="first_name" value="<?= $user->first_name; ?>"><br>
                Prezime:<br><input type="text" name="last_name" value="<?= $user->last_name; ?>"><br>
                E-mail:<br><input type="text" name="email" value="<?= $user->email; ?>"><br>
                Ponovite e-mail:<br><input type="text" name="email" value="<?= $user->email; ?>"><br>
                Password:<br><input type="password" name="password"><? $this->flashSession->output() ?><br>
                Ponovite password:<br><input type="password" name="password"><br>
                <br><input type="submit" value="Submit">
            </form>
        </div>
    </div>
</div>