<div class="container row">
	<div class="card bg-light text-dark" style="margin-left: 30%; margin-top: 5%; width: 27%;">
		<div class="card-body">
			<b>Ime:</b><br><? echo $user->first_name; ?><br>
			<b>Prezime:</b><br><? echo $user->last_name; ?><br>
			<b>E-mail:</b><br><? echo $user->email; ?><br>

			<h4 class="card-title" style="text-align: center;">
               <a class="card-link" href="/user/edit">Uredi</a>
			</h4>
		</div>
	</div>
</div>