<!DOCTYPE html>
<html>
<head>
	<title>LOG IN</title>
	<?php $this->assets->outputCss();?>
</head>
<body>

<div id="fb-root"></div>
<script>

(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/hr_HR/sdk.js#xfbml=1&version=v2.11&appId=532305030462501';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>


<!--
- MOZDA BOLJE PREPISATI SAMO U HTML-u
- DODATI LINKOVE NA SVE BUTTONE
 -->
 <?php echo $this->session->get("user");?>
	<div class = "conatiner login well" align = "center">
		<h2><b>PRIJAVA</b></h2>
		<?php echo $this->tag->form("login/login"); ?>
		<div class = "form-group">
			<label for = "Email">Email: </label>
			<br>
			<?php echo $this->tag->textField(["email","class" => "form-control"]); ?>			
		</div>
		<div class = "form-group">
			<label for = "Password">Password: </label>
			<br>
			<?php echo $this->tag->passwordField(["password","class"=>"form-control"]); ?>			
		</div>
		<div class = "btn-group">
			<button class = "btn btn-success login-btn">Prijava</button>
		</div>		
		<?php echo $this->tag->endForm(); ?>
		<br>
		<div class="fb-login-button" data-width="150" data-max-rows="1" data-size="large" data-button-type="login_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false"></div>
		<br>
		<br>
		<a class = "btn btn-info login-btn" role = "button" href="signup">Registracija</a>
		<a href="index" class = "btn btn-danger login-btn">Povratak</a>
	</div>

</body>
</html>