<!DOCTYPE html>
<html>
<head>
	<title>Mapa</title>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
	<meta charset="utf-8" />
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
</head>

<body>
  <?php include("../app/includes/base.php"); ?>
<div class = "container" height=400px>
  <iframe width=50% height=350px src="https://www.google.com/maps/embed/v1/place?q=<?php echo $address; ?>
      &zoom=16
      &key=AIzaSyAFjIZDe8vEiCE99V5Sl7xxKXlhyOts_ew">
  </iframe>
</div>

</body>
</html>
